export default [
  {
    name: 'Allegro',
    rate: '5',
    foodType: 'Italian',
    deliveryTime: '30-50 min',
    deliveryTax: '15.00',
  },
  {
    name: 'Bellyful',
    rate: '2',
    foodType: 'Chinese',
    deliveryTime: '15-25 min',
    deliveryTax: '5.00',
  },
  {
    name: 'Deep dish',
    rate: '4',
    foodType: 'pizza',
    deliveryTime: '20-40 min',
    deliveryTax: '5.00',
  },
  {
    name: 'Delicious',
    rate: '4',
    foodType: 'vegetarian',
    deliveryTime: '5-15 min',
    deliveryTax: '10.00',
  },
  {
    name: 'Dim sum house',
    rate: '4',
    foodType: 'Chinese',
    deliveryTime: '15-20 min',
    deliveryTax: '5.00',
  },
  {
    name: 'Enchantment under the sea',
    rate: '3',
    foodType: 'seafood',
    deliveryTime: '35-45 min',
    deliveryTax: '10.00',
  },
  {
    name: 'Freshness',
    rate: '3',
    foodType: 'vegetarian',
    deliveryTime: '20-30 min',
    deliveryTax: '4.00',
  },
  {
    name: 'euPHOria',
    rate: '3',
    foodType: 'Vietnamese',
    deliveryTime: '20-25 min',
    deliveryTax: '2.00',
  },
  {
    name: 'Food for thought',
    rate: '5',
    foodType: 'vegetarian',
    deliveryTime: '5-10 min',
    deliveryTax: '10.00',
  },
  {
    name: 'Green world',
    rate: '4',
    foodType: 'vegetarian',
    deliveryTime: '10-20 min',
    deliveryTax: '5.00',
  },
  {
    name: 'Holy smoke!',
    rate: '4',
    foodType: 'Brazilian barbecue',
    deliveryTime: '10-15 min',
    deliveryTax: '7.50',
  },
  {
    name: 'Hoshi sushi',
    rate: '3',
    foodType: 'Japanese',
    deliveryTime: '40-50 min',
    deliveryTax: '10.00',
  },
  {
    name: 'Hot hot heat!',
    rate: '3',
    foodType: 'Mexican',
    deliveryTime: '10-15 min',
    deliveryTax: '5.00',
  },
  {
    name: 'Lemongrass',
    rate: 3,
    foodType: 'vegetarian',
    deliveryTime: '10-15 min',
    deliveryTax: '10.00',
  },
  {
    name: 'Lord of the pizzas',
    rate: 4,
    foodType: 'pizza',
    deliveryTime: '30-40 min',
    deliveryTax: '5.00',
  },
  {
    name: 'Mamma Mia!',
    rate: '4',
    foodType: 'Italian',
    deliveryTime: '30-40 min',
    deliveryTax: '7.50',
  },
  {
    name: 'Meat lovers',
    rate: '4',
    foodType: 'Brazilian barbecue',
    deliveryTime: '10-25 min',
    deliveryTax: '5.00',
  },
  {
    name: 'Paradise found',
    rate: '5',
    foodType: 'Brazilian barbecue',
    deliveryTime: '30-40 min',
    deliveryTax: '10.00',
  },
  {
    name: 'Paradiso',
    rate: '5',
    foodType: 'Italian',
    deliveryTime: '50-60 min',
    deliveryTax: '15.00',
  },
  {
    name: 'Pho king good',
    rate: '3',
    foodType: 'Vietnamese',
    deliveryTime: '10-20 min',
    deliveryTax: '4.00',
  },
  {
    name: 'Piazza pizza',
    rate: '3',
    foodType: 'pizza',
    deliveryTime: '30-40 min',
    deliveryTax: '7.00',
  },
  {
    name: 'Pizza paradise',
    rate: '4',
    foodType: 'pizza',
    deliveryTime: '20-30 min',
    deliveryTax: '10.00',
  },
  {
    name: 'Pizza town',
    rate: '3',
    foodType: 'pizza',
    deliveryTime: '20-30 min',
    deliveryTax: '5.75',
  },
  {
    name: 'Prawness',
    rate: 5,
    foodType: 'seafood',
    deliveryTime: '40-50 min',
    deliveryTax: '10.00',
  },
  {
    name: 'Secret garden',
    rate: 5,
    foodType: 'Chinese',
    deliveryTime: '10-20 min',
    deliveryTax: '6.00',
  },
  {
    name: 'Soyokaze',
    rate: '5',
    foodType: 'Japanese',
    deliveryTime: '5-15 min',
    deliveryTax: '10.00',
  },
  {
    name: 'Sushimania',
    rate: '5',
    foodType: 'Japanese',
    deliveryTime: '5-10 min',
    deliveryTax: '15.00',
  },
  {
    name: 'Sushi heaven',
    rate: '4',
    foodType: 'Japanese',
    deliveryTime: '10-15 min',
    deliveryTax: '20.00',
  },
  {
    name: 'Sushi strikes back',
    rate: '5',
    foodType: 'Japanese',
    deliveryTime: '35-40 min',
    deliveryTax: '10.00',
  },
  {
    name: 'The godfather',
    rate: '3',
    foodType: 'Italian',
    deliveryTime: '20-30 min',
    deliveryTax: '7.00',
  },
  {
    name: 'The great wall of China',
    rate: '2',
    foodType: 'Chinese',
    deliveryTime: '10-25 min',
    deliveryTax: '3.50',
  },
];
