export default [
  {
    id: 0,
    name: 'Allegro',
    rate: '5',
    foodType: 'Italian',
    deliveryTime: '30-50 min',
    deliveryTax: '15.00',
  },
  {
    id: 1,
    name: 'Bellyful',
    rate: '2',
    foodType: 'Chinese',
    deliveryTime: '15-25 min',
    deliveryTax: '5.00',
  },
  {
    id: 2,
    name: 'Deep dish',
    rate: '4',
    foodType: 'pizza',
    deliveryTime: '20-40 min',
    deliveryTax: '5.00',
  },
  {
    id: 3,
    name: 'Delicious',
    rate: '4',
    foodType: 'vegetarian',
    deliveryTime: '5-15 min',
    deliveryTax: '10.00',
  },
  {
    id: 4,
    name: 'Dim sum house',
    rate: '4',
    foodType: 'Chinese',
    deliveryTime: '15-20 min',
    deliveryTax: '5.00',
  },
  {
    id: 5,
    name: 'Enchantment under the sea',
    rate: '3',
    foodType: 'seafood',
    deliveryTime: '35-45 min',
    deliveryTax: '10.00',
  },
  {
    id: 6,
    name: 'Freshness',
    rate: '3',
    foodType: 'vegetarian',
    deliveryTime: '20-30 min',
    deliveryTax: '4.00',
  },
  {
    id: 7,
    name: 'euPHOria',
    rate: '3',
    foodType: 'Vietnamese',
    deliveryTime: '20-25 min',
    deliveryTax: '2.00',
  },
  {
    id: 8,
    name: 'Food for thought',
    rate: '5',
    foodType: 'vegetarian',
    deliveryTime: '5-10 min',
    deliveryTax: '10.00',
  },
  {
    id: 9,
    name: 'Green world',
    rate: '4',
    foodType: 'vegetarian',
    deliveryTime: '10-20 min',
    deliveryTax: '5.00',
  },
  {
    id: 10,
    name: 'Holy smoke!',
    rate: '4',
    foodType: 'Brazilian barbecue',
    deliveryTime: '10-15 min',
    deliveryTax: '7.50',
  },
  {
    id: 11,
    name: 'Hoshi sushi',
    rate: '3',
    foodType: 'Japanese',
    deliveryTime: '40-50 min',
    deliveryTax: '10.00',
  },
  {
    id: 12,
    name: 'Hot hot heat!',
    rate: '3',
    foodType: 'Mexican',
    deliveryTime: '10-15 min',
    deliveryTax: '5.00',
  },
  {
    id: 13,
    name: 'Lemongrass',
    rate: '3',
    foodType: 'vegetarian',
    deliveryTime: '10-15 min',
    deliveryTax: '10.00',
  },
  {
    id: 14,
    name: 'Lord of the pizzas',
    rate: 4,
    foodType: 'pizza',
    deliveryTime: '30-40 min',
    deliveryTax: '5.00',
  },
  {
    id: 15,
    name: 'Mamma Mia!',
    rate: '4',
    foodType: 'Italian',
    deliveryTime: '30-40 min',
    deliveryTax: '7.50',
  },
  {
    id: 16,
    name: 'Meat lovers',
    rate: '4',
    foodType: 'Brazilian barbecue',
    deliveryTime: '10-25 min',
    deliveryTax: '5.00',
  },
  {
    id: 17,
    name: 'Paradise found',
    rate: '5',
    foodType: 'Brazilian barbecue',
    deliveryTime: '30-40 min',
    deliveryTax: '10.00',
  },
  {
    id: 18,
    name: 'Paradiso',
    rate: '5',
    foodType: 'Italian',
    deliveryTime: '50-60 min',
    deliveryTax: '15.00',
  },
  {
    id: 19,
    name: 'Pho king good',
    rate: '3',
    foodType: 'Vietnamese',
    deliveryTime: '10-20 min',
    deliveryTax: '4.00',
  },
  {
    id: 20,
    name: 'Piazza pizza',
    rate: '3',
    foodType: 'pizza',
    deliveryTime: '30-40 min',
    deliveryTax: '7.00',
  },
  {
    id: 21,
    name: 'Pizza paradise',
    rate: '4',
    foodType: 'pizza',
    deliveryTime: '20-30 min',
    deliveryTax: '10.00',
  },
  {
    id: 22,
    name: 'Pizza town',
    rate: '3',
    foodType: 'pizza',
    deliveryTime: '20-30 min',
    deliveryTax: '5.75',
  },
  {
    id: 23,
    name: 'Prawness',
    rate: 5,
    foodType: 'seafood',
    deliveryTime: '40-50 min',
    deliveryTax: '10.00',
  },
  {
    id: 24,
    name: 'Secret garden',
    rate: 5,
    foodType: 'Chinese',
    deliveryTime: '10-20 min',
    deliveryTax: '6.00',
  },
  {
    id: 25,
    name: 'Soyokaze',
    rate: '5',
    foodType: 'Japanese',
    deliveryTime: '5-15 min',
    deliveryTax: '10.00',
  },
  {
    id: 26,
    name: 'Sushimania',
    rate: '5',
    foodType: 'Japanese',
    deliveryTime: '5-10 min',
    deliveryTax: '15.00',
  },
  {
    id: 27,
    name: 'Sushi heaven',
    rate: '4',
    foodType: 'Japanese',
    deliveryTime: '10-15 min',
    deliveryTax: '20.00',
  },
  {
    id: 28,
    name: 'Sushi strikes back',
    rate: '5',
    foodType: 'Japanese',
    deliveryTime: '35-40 min',
    deliveryTax: '10.00',
  },
  {
    id: 29,
    name: 'The godfather',
    rate: '3',
    foodType: 'Italian',
    deliveryTime: '20-30 min',
    deliveryTax: '7.00',
  },
  {
    id: 30,
    name: 'The great wall of China',
    rate: '2',
    foodType: 'Chinese',
    deliveryTime: '10-25 min',
    deliveryTax: '3.50',
  },
];
